### PR TITLE
Mount buildkite agent into build container

### PR DESCRIPTION
**Pull request by geigerzaehler**
I would like to use `buildkite-agent annotate` from builds.

### CODE REVIEW

**Comment by geigerzaehler** [comment]
So this requires the buildkite agent token, too. Not sure how safe it is to expose it.

**Comment by kim** [comment]
Yeah so I think there isn’t much damage that can be done with the token - everything is scoped to the build in one way or another. 

However, the token is effectively scoped to the organisation - so if the above assessment isn’t true because we missed something, or there’s some vulnerability on BK’s side, all projects will be affected. I would thus be more comfortable if the token was only exposed to “trusted” builds (much like secrets). You can put a conditional in the build script to check for a third party PR if you ticked the “Prefix branch name” in the pipeline settings.

**Comment by geigerzaehler** [comment]
Sounds reasonable to only expose the token to trusted builds.

> You can put a conditional in the build script to check for a third party PR if you ticked the “Prefix branch name” in the pipeline settings.

Can’t we check for trusted builds with this also?
https://github.com/oscoin/ci/blob/4dcfb5bacd70c79a9ba29c1af981ca3ee49fb7fc/linux/etc/buildkite-agent/hooks/command#L117-L118

**Comment by kim** [comment]
> Can’t we check for trusted builds with this also?

True, although the build script may not want to rely on what the value of `TRUSTED_UPSTREAMS_REGEX` is

**Comment by geigerzaehler** [comment]
The buildkite token is now only available for trusted builds.

**Pull request merged**
